# Generated by Django 5.2.5 on 2025-10-26 04:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_options_remove_account_account_id_and_more'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount_requested',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='reviewed_at',
            new_name='approved_at',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loan',
            name='duration_months',
            field=models.PositiveIntegerField(default='12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('repaid', 'Repaid')], default='pending', max_length=20),
        ),
    ]
