# Generated by Django 5.2.5 on 2025-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_amount_requested_loan_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The total amount requested by the user.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when loan was approved.', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration_months',
            field=models.PositiveIntegerField(default=12, help_text='Loan repayment duration in months.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Interest rate in percentage.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REPAID', 'Repaid')], default='PENDING', max_length=20),
        ),
    ]
